package enity;

import java.math.BigDecimal;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.number
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.repertory
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    private Integer repertory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.price
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.getegory
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    private String getegory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.number
     *
     * @return the value of commodity.number
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.number
     *
     * @param number the value for commodity.number
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.repertory
     *
     * @return the value of commodity.repertory
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public Integer getRepertory() {
        return repertory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.repertory
     *
     * @param repertory the value for commodity.repertory
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public void setRepertory(Integer repertory) {
        this.repertory = repertory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price
     *
     * @return the value of commodity.price
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.getegory
     *
     * @return the value of commodity.getegory
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public String getGetegory() {
        return getegory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.getegory
     *
     * @param getegory the value for commodity.getegory
     *
     * @mbg.generated Tue Jun 12 18:09:32 CST 2018
     */
    public void setGetegory(String getegory) {
        this.getegory = getegory;
    }
}